defaults: []

source: vnstock # vnstock for VN market (cafe.vn)
universe: VN30

symbols:
  vn30:
    - "ACB"
    - "BCM"
    - "BID"
    - "BVH"
    - "CTG"
    - "FPT"
    - "GAS"
    - "GVR"
    - "HDB"
    - "HPG"
    - "MBB"
    - "MSN"
    - "MWG"
    - "PLX"
    - "POW"
    - "SAB"
    - "SHB"
    - "SSB"
    - "SSI"
    - "STB"
    - "TCB"
    - "TPB"
    - "VCB"
    - "VHM"
    - "VIB"
    - "VIC"
    - "VJC"
    - "VNM"
    - "VPB"
    - "VRE"
  custom: []

price:
  fields: [open, high, low, close, volume]
  adjust: true # adjusted prices

cache: true
