defaults:
  - base
  - data
  - features
  - cluster_hclust
  - optimizer_markowitz
  - _self_

project: vn50-hclust-markowitz-demo

calendar:
  start: "2020-11-09"
  end: "2025-10-31"
  frequency: D
